---
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  env: readonly
  apiUrl: readonly
  authDomain: readonly
  authClientId: readonly
  authAudience: readonly
  urls: readonly
  Chart: readonly
rules:
  import/no-unresolved: 0
  no-continue: 0
  no-console: 1
  no-shadow: 0
  consistent-return: 0
  use-isnan: 2
  valid-typeof: 2
  no-underscore-dangle: 0
  curly:
    - 2
    - multi-or-nest
  no-var: 2
  one-var: 0
  no-undef: 2
  react/display-name: 0
  arrow-body-style:
    - 2
    - as-needed
  arrow-parens:
    - 2
    - as-needed
  arrow-spacing: 2
  brace-style: 2
  comma-spacing: 2
  comma-style: 2
  key-spacing:
    - 2
    - beforeColon: false
      afterColon: true
  no-nested-ternary: 0
  no-new-object: 2
  semi-spacing:
    - 2
    - before: false
      after: true
  object-curly-newline: 0
  no-trailing-spaces: 2
  no-multiple-empty-lines: 2
  no-unused-vars: 1
  operator-assignment:
    - 2
    - always
  quotes:
    - 2
    - single
    - avoidEscape: true
  quote-props:
    - 2
    - as-needed
  semi:
    - 2
    - always
  sort-vars:
    - 2
    - ignoreCase: true
  keyword-spacing: 2
  space-before-blocks: 2
  object-curly-spacing:
    - 2
    - always
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  max-len:
    - 2
    - 120
    - ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreComments: true
  no-prototype-builtins: 2
  react/require-default-props: 0
  react/forbid-prop-types: 0
  react/button-has-type: 0
  react/no-array-index-key: 0
  react/jsx-props-no-spreading: 0
  react/no-unused-prop-types: 0
  react/no-unknown-property:
    - 2
    - ignore: ["css"]
  react/prop-types:
    - 2
    - skipUndeclared: true
  react/self-closing-comp: 1
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/label-has-for: 0
  no-confusing-arrow: 0
  implicit-arrow-linebreak: 0
  no-unused-expressions:
    - 2
    - enforceForJSX: true
      allowTaggedTemplates: true
      allowShortCircuit: true
      allowTernary: true
  no-plusplus: 0
  no-use-before-define: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
